services:
  - type: web
    name: sdui-user-management
    runtime: static
    rootDir: sites/user-management
    buildCommand: cd ../.. && pnpm install && pnpm --filter "./packages/*" run build && pnpm --filter sdui-site-user-management run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
